# Поддержка проекта Document Viewer
# Раскомментируйте и добавьте ваши ссылки для поддержки проекта

# github: [ваш-username]
# patreon: ваш-username
# ko_fi: ваш-username
# custom: ['https://www.paypal.me/username', 'https://link-to-your-site']

